### ISSUE TITLE
More styling (incorporate css); make pages more aesthetically pleasing

### ISSUE THREAD

**Issue by Stanleyy03840** [yolandayangg/m223coders#12]

**Comment by yolandayangg** [comment]
![Screen Shot 2021-11-05 at 7 08 50 AM](https://user-images.githubusercontent.com/89219568/140533587-214ed14d-64c8-48fb-a588-75504bfd8258.png
![Screen Shot 2021-11-05 at 6 56 12 AM](https://user-images.githubusercontent.com/89219568/140533621-9ad28ec7-dc97-42a8-85cb-2962728dd2c2.png)
)
