### ISSUE TITLE
(tianbin)week 9 individual final video

### ISSUE THREAD

**Issue by TianbinLiu** [yolandayangg/m223coders#14]
https://drive.google.com/file/d/1-PesUeIhunv6GLTu-PbdSOoqENSA5M_A/view?usp=sharing

**Comment by jm1021** [comment]
Reviewer John Mortensen.
Grading: Tianbin

1.) Program purpose gives a tour and some key features of  the site.
2.) Collaboration highlights GitHub and help from teammate Stanley.  
3.) Iteration show line of code that does not show iterations, it shows abstraction of line of code.  Lazy programmer concept is mentioned, but I am a little confused.  

I believe this is good chat by Tianbin and shows growth through Trimester.  However, there are some details that could be worked on more fully.   1.) Clear purpose or intro, does this well. 2.) Make sure to show code or tangibles to back up purpose, this seems to be off on Iteration example. 3.) Show a related demo, not sure I got this on iteration.

5.25/6 as there are major deductions on Iteration example and this was the KEY Technical topic.

**Comment by jm1021** [comment]
Regarding comments.   I would like to see them more specific.  For instance, on Justin's you could have suggested topics.
