### ISSUE TITLE
Stanley: Week 9 Video

### ISSUE THREAD

**Issue by Stanleyy03840** [yolandayangg/m223coders#16]
[Video](https://youtu.be/68koUJPXuQ0)

**Comment by shrutiapcsp** [comment]
Hi Stanley,

Here are some comments I have on your video presentation

Postives:

- I like how organized your overall presentation was. You could clearly tell that you prepared for this presentation in advance and having the code along with a background on each of the topics made each concept very easy to understand
- I enjoyed your description of the binary page. Including an image of your code that used minary conversions along side your website made it clear that you understood the code and how it influenced your page
- Your explanation of SIgned Addition was thorough. I liked how you explained each line of code. I would be interested to see if some of your mini-lab work could be implemented into your PBL project

Improvement:
- For topic 1.3, you quickly scrolled through the code. Would have been better to go in depth and explain the program before showing the runtime. You could also see how some of your mini-lab work could be implemented into your PBL maybe doing something with hexcode and conversions with bianry for the colors of the books.


Here are my overall grades:
Topic 1: 1.5/2 (more explanation of code)
Topic 2: 2/2
Topic 3: 2/2

Overall: 5.5/6
Great job!

**Comment by shrutiapcsp** [comment]
Comments have references however some don't explain why or where you took off points. Splitting up your comments for improvements and positives would have been easier to understand. 
Grade: 1.75/2

**Comment by jm1021** [comment]
Stanley, I like your presentation a lot.  You prepared topics and had a nice flow throughout.   I like how you shared plans to reality in 1st segment which covered topic well.   Binary technical explanations were very good on CB required material on binary and conversions.  Last two segments you identified code correctly to match topic.  5.75/6.  1.75/2 on comments as indicated above.
